version: '3.8'

services:
  avantgraph:
    container_name: avantgraph
    image: stijnking/avantgraph-mpg:latest
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    ports:
      - "7687:7687"
    volumes:
      - ./data:/data
    command: >
      sh -c "ag-server --listen=0.0.0.0:7687 /data/snb-bi"
    working_dir: /
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 20G
